### ISSUE TITLE
Avoid this

### ISSUE THREAD

**Issue by belliel** [link1107/DonationExecutor#15]
https://github.com/link1107/DonationExecutor/blob/4a643213e22dc741057620d3007f58ab024faa8c/src/main/java/igorlink/service/MainConfig.java#L72-L76

https://www.programcreek.com/java-api-examples/?class=org.bukkit.configuration.file.FileConfiguration&method=getBoolean

```java
twitchFilter = config.getString("TwitchFilter") == "true";
// or use
twitchFilter = config.getBoolean("TwitchFilter");
```

**Comment by link1107** [comment]
Спасибо, фиксанул
