### ISSUE TITLE
Переписать приложение на чистый Assembler

### ISSUE THREAD

**Issue by LeftTwixWand** [link1107/DonationExecutor#24]
Использование [JVM (Java Virtual Machine)](https://ru.wikipedia.org/wiki/Java_Virtual_Machine) и её преимуществ, по типу автоматического управления памятью, независимость от платформы, да и в целом других преимуществ интерпретируемых языков является слишком ресурсозатратным.

В наши дни такая роскошь - непозволительна.
Ведь каждый Ватт энергии, который тратится на лишние вычисления, дабы облегчить жизнь программистам - это:
- сожжённый уголь в ТЭС;
- загрязнение природы радиоактивными отходами с атомных станций; 
- вырубленные деревьев;
- высушенные ради лития, земли;
- **это ГЛОБАЛЬНОЕ ПОТЕПЛЕНИЕ!**

Спорить с этим бесполезно, так, как со мной будут согласны все авторитетные и неподкупные эко активисты:

![image](https://user-images.githubusercontent.com/50652041/153241801-f752b383-9814-4ff6-99e7-8f48332e9ca9.png)

Как итог - считаю, что рантайм джавы слишком не экологичный, и весь проект нужно переписать на Ассемблер.
Документация ассемблера: [ibm.com/docs/en/aix/7.1](https://www.ibm.com/docs/en/aix/7.1?topic=aix-assembler-language-reference)

**Comment by nialek** [comment]
Мне нравится твой дух, но предлагаю пойти еще дальше: переписать плагин на комбинационную схему!
