### ISSUE TITLE
Не работает на Spigot(?)

### ISSUE THREAD

**Issue by MarkG1M** [link1107/DonationExecutor#29]
Поднял локальный сервак на spigot'е, он выдал следующее:
 Plugin DonationExecutor v0.3.4 has failed to register events for class igorlink.donationexecutor.executionsstaff.giantmobs.GiantMobEventListener because io/papermc/paper/event/entity/EntityMoveEvent does not exist.

**Comment by link1107** [comment]
Какой версии сервер?

**Comment by link1107** [comment]
Проверил - на спиготе больше действительно не работает (плагин использует методы из API ядра Paper, которых нет в API ядра Spigot). Советую просто заменить Spigot на Paper.
