### ISSUE TITLE
You might want to create a LICENSE file

### ISSUE THREAD

**Issue by burmistrov-tech** [link1107/DonationExecutor#3]
В твоём README указано:

> "Могу ли я изменить/дополнить этот код и использовать его в коммерческих целях?"

Соглашение о распространении твоего кода ты можешь указать через LICENSE файл, подробнее прочитать можно тут:

- https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

В выборе лицензии может помочь: https://choosealicense.com
Текущие условия репозитория: https://choosealicense.com/no-permission/

**Comment by nburmistrov** [comment]
Также, если ты планируешь получать Pull Request от других пользователей (не увидел в README) ,то можешь добавить [Contribution Guidline](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors)

**Comment by link1107** [comment]
Спасибо. Знаю про лицензию, но я пока еще не выбрал ее, поэтому пока запостил без лицензии вообще. До гайдлайнов тоже руки пока не дошли.

**Comment by s3ponia** [comment]
> Также, если ты планируешь получать Pull Request от других пользователей (не увидел в README) ,то можешь добавить [Contribution Guidline](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors)

Лучше попросить кого-то другого гайдлайны написать или скопипастить откуда-нибудь

**Comment by link1107** [comment]
> > Также, если ты планируешь получать Pull Request от других пользователей (не увидел в README) ,то можешь добавить [Contribution Guidline](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors)
> 
> Лучше попросить кого-то другого гайдлайны написать или скопипастить откуда-нибудь

Попрошу кого-то - начнут опять говорить, что не я все делаю, а за меня кто-то делат. Скопипасчу - начнут орать, что украл и сплагиатил.

**Comment by Portunis** [comment]
> > > Также, если ты планируешь получать запрос на вытягивание от других пользователей (не увидел в README), то можешь добавить [Руководство по внесению вклада](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors)
> > 
> > 
> > Лучше попросить кого-то другого гайдлайны написать или скопипастить откуда-нибудь
> 
> Попрошу кого-то - начни опять говорить, что не я все делаю, а за меня кто-то делат. Скопипасчу - начни орать, что украл и сплагиатил.

Ты можешь не просто скопипастить, а подглядеть, переделать под себя. Такая практика приветствуется. Зачем придумывать новый велосипед, если  уже есть готовое решение. Самое главное - понимать, как это работает, а не тупо ctrl c ctrl v

**Comment by link1107** [comment]
Добавил AGPL 3.0
