### ISSUE TITLE
Токен донейшн алертса.

### ISSUE THREAD

**Issue by noremac09** [link1107/DonationExecutor#7]
Не совсем понимаю, зачем в плагине возможность добавлять несколько стримеров в конфиге, но сам плагин написан под работу только с ОДНИМ токеном. 

Изначально думал что это будет стоять на каком-то сервере, где может играть одновременно 2-3 стримера, если задумка такая - увы, это не будет работать. Нужно дописать так, чтобы под каждого стримера устанавливался свой токен.

**Comment by link1107** [comment]
> Не совсем понимаю, зачем в плагине возможность добавлять несколько стримеров в конфиге, но сам плагин написан под работу только с ОДНИМ токеном. 
> 
> Изначально думал что это будет стоять на каком-то сервере, где может играть одновременно 2-3 стримера, если задумка такая - увы, это не будет работать. Нужно дописать так, чтобы под каждого стримера устанавливался свой токен.

В планах на ближайшие версии.

**Comment by Kanorto** [comment]
Присоединюсь к человеку, очень нужно.

**Comment by link1107** [comment]
Добавлено с новым релизом
