### ISSUE TITLE
Ошибочное использование Bukkit.getPlayer()

### ISSUE THREAD

**Issue by serega6531** [link1107/DonationExecutor#8]
В плагине используется Bukkit.getPlayer для получения игрока по нику. На самом деле ты хочешь использовать getPlayerExact, иначе в некоторых случаях ты будешь получать не тех игроков. getPlayer возвращает игрока, ник которого начинается с определенной строки (https://bukkit.org/threads/getplayer-exact.26696/), а getPlayerExact - с этим конкретным ником.
Например, если ты отправил донат для igorlink, но при этом был не на сервере, то он придет игроку с ником вроде igorlink123, если он окажется на сервере.

**Comment by link1107** [comment]
Fixed
